myforum/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('myforum.views',
    url(r'^signup/', 'signup', name='signup'),
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    
    url(r'^$', 'index', name='index'),
    url(r'^forum/(?P<slug>[\w-]+)/$', 'forum_detail', name='forum'),
    url(r'^topic/new/$', 'new_topic', name='new_topic'),
    url(r'^topic/(?P<slug>[\w-]+)/$', 'topic_detail', name='topic'),
    url(r'^search/$', 'search', name='search'),
    url(r'^post/(\d+)/delete/$', 'delete_post', name='delete_post'),
    url(r'^post/(\d+)/edit/$', 'edit_post', name='edit_post'),
    
)

simple_forum/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', include('myforum.urls', namespace='myforum')),
    url(r'^', include('myforum.urls', namespace='myforum')),
    
)

from django.conf import settings as s

urlpatterns += patterns('django.views.static',
    (r'^static/(?P<path>.*)$', 'serve', {'document_root': s.STATIC_ROOT}),
    (r'^media/(?P<path>.*)$', 'serve', {'document_root': s.MEDIA_ROOT}),
)

myforum/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django_extensions.db.models import (
    TimeStampedModel,           # created, modified
    TitleSlugDescriptionModel,  # title, slug, description
    ActivatorModel,                  # status, activate_date, deactivate_date
)


class AWS(models.Model):
    key = models.CharField(max_length=200)
    value = models.CharField(max_length=200, blank=True)
    
    def __unicode__(self):
        return self.key
    
    class Meta:
        verbose_name_plural = 'AWS'
    
    @classmethod
    def access_key(cls):
        return cls.objects.get(key='AWS_ACCESS_KEY_ID').value or getattr(settings, 'AWS_ACCESS_KEY_ID', '')
    
    @classmethod
    def access_key_secret(cls):
        return cls.objects.get(key='AWS_SECRET_ACCESS_KEY').value or getattr(settings, 'AWS_SECRET_ACCESS_KEY', '')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to='avatar', blank=True)
    
    def __unicode__(self):
        return self.user.username

class Forum(TitleSlugDescriptionModel, ActivatorModel):
    order = models.IntegerField(default=9)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ('order', )
    
    @models.permalink
    def get_absolute_url(self):
        return ('myforum:forum', [self.slug])
    
    def topics_count(self):
        return models.get_model('myforum', 'topic').objects.active().filter(forum=self).count()

class Topic(TimeStampedModel, TitleSlugDescriptionModel, ActivatorModel):
    forum = models.ForeignKey(Forum, null=True, blank=True)
    created_by = models.ForeignKey(User)
    order = models.IntegerField(default=9)
    arn = models.CharField(max_length=200, blank=True)
    
    def __unicode__(self):
        return self.title
    
    class Meta:
        ordering = ('order', '-created')
    
    @models.permalink
    def get_absolute_url(self):
        return ('myforum:topic', [self.slug])
    
    def posts(self):
        return Post.objects.active().filter(topic=self)
    
    def is_first_time_post_by(self, user):
        '''return if user first time post for the topic'''
        return user.pk not in self.post_set.all().values_list('created_by', flat=True)
    
    def save(self, **kwargs):
        super(Topic, self).save(**kwargs)
        
        try:
            import boto
            conn = boto.connect_sns(AWS.access_key(), AWS.access_key_secret())
            res = conn.create_topic(self.slug.encode('utf8'))
            arn = res['CreateTopicResponse']['CreateTopicResult']['TopicArn']
            self.arn = arn
            super(Topic, self).save(update_fields=['arn'])
        except:
            pass

class Post(TimeStampedModel, ActivatorModel):
    topic = models.ForeignKey(Topic)
    content = models.TextField()
    created_by = models.ForeignKey(User)
    
    def __unicode__(self):
        return self.created_by.username + ' said:'
    
    class Meta:
        ordering = ('-created', )
    
    def avatar_url(self):
        try:
            return self.created_by.userprofile.avatar.url
        except:
            return '/static/myforum/thumb_default_31_31.jpg'

myforum/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.http import Http404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, login as auth_login, authenticate
from django.contrib.auth.views import login as auth_login_view
from django.contrib.auth.forms import AuthenticationForm
from django.core.validators import email_re
from django.contrib.auth.models import User

from myforum.models import Forum, Topic, Post, AWS
from myforum.templatetags.myforum_tags import can_edit, can_delete


def signup(request):
    if request.method == 'POST':
        data = request.POST
        if 'email' in data and email_re.search(data['email']):
            username = data.get('username', '')
            password = data.get('password', '')
            email = data['email']
            User.objects.create_user(username, email, password)
            return redirect('myforum:index')
    
    return render(request, 'myforum/signup.html')

def login(request):
    if request.method == 'POST':
        data = request.POST
        if 'email' in data and email_re.search(data['email']):
            password = data.get('password', '')
            email = data['email']
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                raise Http404('User does not exist')
            user = authenticate(username=user.username, password=password)
            if user:
                auth_login(request, user)
            else:
                raise Http404('Invalid password')
            return redirect('myforum:index')
    
    return render(request, 'myforum/login.html')

def login_with_username(request):
    defaults = {
        'template_name': 'admin/login.html',
        'authentication_form': AuthenticationForm,
    }
    return auth_login_view(request, **defaults)

def logout(request):
    auth_logout(request)
    return redirect(request.GET.get('next') or 'myforum:index')

def index(request):
    '''
    List topics
    '''
    context = {
        'topics': Topic.objects.active(),
    }
    return render(request, 'myforum/index.html', context)

def forum_detail(request, slug):
    '''
    List topics of forum
    '''
    current_forum = get_object_or_404(Forum.objects.active(), slug=slug)
    context = {
        'current_forum': current_forum,
        'topics': Topic.objects.active().filter(forum=current_forum),
    }
    return render(request, 'myforum/index.html', context)

def topic_detail(request, slug):
    '''
    List topic posts, or create new post if POST method
    '''
    
    current_topic = get_object_or_404(Topic.objects.active(), slug=slug)
    
    # create new post
    if request.method == 'POST':
        if not request.user.is_authenticated():
            return redirect(resolve_url('myforum:login')+'?next='+request.get_full_path())
        
        post = request.POST.get('post', '').strip()
        if len(post) > 0:
            is_first_time_post = current_topic.is_first_time_post_by(request.user)
            Post.objects.create(topic=current_topic, content=post, created_by=request.user)
            
            try:
                arn = current_topic.arn.strip()
                email = request.user.email
                if len(arn) > 0 and email_re.search(email):
                    import boto
                    conn = boto.connect_sns(AWS.access_key(), AWS.access_key_secret())
                    if is_first_time_post:
                        conn.subscribe(arn, 'email', email)
                    myname = request.user.get_full_name() or request.user.username
                    myname = myname.encode('utf8')
                    conn.publish(arn, myname+' said: \n\n'+post.encode('utf8'), myname+' reply to '+current_topic.title.encode('utf8'))
            except:
                pass
        return redirect('myforum:topic', slug=slug)
    
    context = {
        'current_topic': current_topic,
    }
    return render(request, 'myforum/topic.html', context)

@require_POST
def search(request):
    keywords = request.POST.get('kw', '').split()
    if len(keywords)==0:
        topics_searched = []
    else:
        topics_searched = Topic.objects.active()
        posts_searched = Post.objects.active()
        
        for kw in keywords:
            topics_searched = topics_searched.filter(title__icontains=kw) | topics_searched.filter(description__icontains=kw)
            posts_searched = posts_searched.filter(content__icontains=kw)
        
        topics_searched = list(topics_searched)
        for post in posts_searched:
            if post.topic not in topics_searched:
                topics_searched.append(post.topic)
    
    context = {
        'topics_searched': topics_searched,
    }
    return render(request, 'myforum/topics_searched.html', context)

@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    topic = post.topic
    if can_delete(request.user, post):
        #~ post.status = Post.INACTIVE_STATUS
        #~ post.save(update_fields=['status'])
        post.delete()
    return redirect(request.GET.get('next') or topic)

@login_required
def edit_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    context = {'post': post}
    
    if not can_edit(request.user, post):
        raise Http404('No rights to edit post')
    if request.method == 'POST' and 'content' in request.POST:
        post.content = request.POST['content']
        post.save(update_fields=['content', 'modified'])
        context['saved'] = 'saved'
    
    return render(request, 'myforum/edit_post.html', context)

@login_required
def new_topic(request):
    slug = request.REQUEST.get('f', '')
    current_forum = get_object_or_404(Forum, slug=slug)
    
    if request.method == 'POST':
        data = request.POST
        if 'title' in data and len(data['title'].strip()) > 0:
            title = data['title']
            content = data.get('content', '')
            topic = Topic(title=title, description=content, created_by=request.user, forum=current_forum)
            topic.save()
            return redirect('myforum:topic', slug=topic.slug)
    
    context = {
        'current_forum': current_forum,
    }
    return render(request, 'myforum/new_topic.html', context)

myforum/templates/myforum/base.html
{% extends 'base.html' %}

{% block content %}

<div id="main">
    <div class="main_middle">
        <div class="forum-container clearfix">
            
            {% block main %}
            {% endblock %}
            
        </div> <!-- .forum-container -->
    </div> <!-- .main_middle -->
</div> <!-- #main -->

<div id="sidebar">
    <!-- <div class="sidebar_top"></div> -->
    <div class="sidebar_middle">
        <div class="sidebar-nav">
            <div id="yw2" class="portlet">
                <div class="nav nav-list">
                    <a href="{% url 'myforum:index' %}" class="nav-header">Forums</a>
                </div>
                <div class="portlet-content">
                    <form method="POST" action="{% url 'myforum:search' %}" id="keywordSearch">
                        {% csrf_token %}
                        <input type="text" placeholder="Search..." class="search_box" name="kw" style="background: url('{{ STATIC_URL }}myforum/search_box_bg.png') no-repeat scroll 0 0 transparent" />
                    </form>
                </div> <!-- .portlet-content -->
            </div> <!-- .portlet -->
        
            <div id="yw3" class="portlet">
                <div class="portlet-content">
                    <div class="list-view" id="yw4">
                        <ul class="nav nav-list">
                        {% for forum in forums %}
                            <li><a href="{{ forum.get_absolute_url }}">{{ forum.title }}</a><span class="topics-count">{{ forum.topics_count }}</span></li>
                        {% endfor %}
                        </ul>
                    </div> <!-- .list-view -->
                </div> <!-- .portlet-content -->
            </div> <!-- .portlet -->
        </div> <!-- .sidebar-nav -->
        
        {% if user.is_authenticated %}
        {% if current_forum %}
        <div>
            <a href="{% url 'myforum:new_topic' %}?f={{ current_forum.slug }}" >New Topic</a>
        </div>
        {% endif %}
        {% endif %}
        
    </div> <!-- .sidebar_middle -->
    <!-- <div class="sidebar_bottom"></div> -->
</div> <!-- #sidebar -->

<div class="clear"></div>

{% endblock %}

myforum/templates/myforum/edit_post.html
{% load myforum_tags %}

<div>
<form method="post" action="">
    {% csrf_token %}
    <textarea name="content" style="width:550px;height:170px;color:#889099">{{ post.content }}</textarea>
    <br />
    <input type="submit" value="Save" />
</form>
</div>

{% if saved %}
<script type="text/javascript">
//~ window.close();

parent.document.location.reload();

</script>
{% endif %}

myforum/templates/myforum/index.html
{% extends 'myforum/base.html' %}
{% load endless %}

{% block main %}

    {% if current_forum %}
    <div class="forum-header" style="border-bottom: 1px solid #F1F1F1; margin: -10px -10px 10px; padding: 25px 20px;">
        <h3 class="forum-title" style="font-size: 20px;color: #59677A; font-weight: bold; height: 40px; line-height: 40px;">{{ current_forum.title }}</h3>
        {{ current_forum.description }}
    </div>
    {% endif %}
    
            <div class="topics-container">
                <div id="yw0" class="list-view">
                    <div class="items">
                        
                        {% paginate topics %}
                        {% for topic in topics %}
                        <div class="topic clearfix odd">
                            <h4 class="topic-title"><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></h4>
                            <p class="topic-description">{{ topic.description }}</p>
                            <ul class="topic-meta">
                                <li class="topic-meta-item"> Created by  {{ topic.created_by }}</li>
                                <li class="topic-meta-item">on {{ topic.created|date:"n/j/y" }}</li>
                                <li class="topic-meta-item">{{ topic.posts|length }} posts</li>
                            </ul>
                        </div>
                        {% endfor %}
                        
                    </div> <!-- .items -->
                    
                    <br />
                    <div style="text-align: right">
                    {% show_pages %}
                    </div>
                    <br />
                    
                    <!--
                    <div class="pager">
                        <ul id="yw1" class="yiiPager">
                            <li class="first hidden"><a href="#">&lt;&lt; First</a></li>
                            <li class="previous hidden"><a href="#"><span class="pagination-left"></span></a></li>
                            <li class="page selected"><a href="#">1</a></li>
                            <li class="page"><a href="#">2</a></li>
                            <li class="next"><a href="#"><span class="pagination-right"></span></a></li>
                            <li class="last hidden"><a href="#">Last &gt;&gt;</a></li>
                        </ul>
                    </div>
                -->
                </div> <!-- .list-view -->
            </div> <!-- .topic-container -->

{% endblock %}

myforum/templates/myforum/login.html
{% extends 'myforum/base.html' %}

{% block main %}
<div>
<form method="post" action="">
{% csrf_token %}
<label>Email: <br /><input type="text" name="email" /></label>
<br />
<br />
<label>Password: <br /><input type="password" name="password" /></label>
<br />
<br />
<input type="submit" value="Login" class="btn btn-primary btn-toolbar" />
</form>
</div>
{% endblock %}

myforum/templates/myforum/new_topic.html
{% extends 'myforum/base.html' %}

{% block main %}
   {% if current_forum %}
    <div class="forum-header" style="border-bottom: 1px solid #F1F1F1; margin: -10px -10px 10px; padding: 25px 20px;">
        <h3 class="forum-title" style="font-size: 20px;color: #59677A; font-weight: bold; height: 40px; line-height: 40px;">{{ current_forum.title }}</h3>
        {{ current_forum.description }}
    </div>
    {% endif %}
    
<div style="padding: 25px 20px;margin: -10px">
<form method="post" action="">
{% csrf_token %}
<label>Title: <br /><input type="text" name="title" /></label>
<br />
<br />
<label>Content: <br /><textarea name="content" style="width:500px;height:80px;color:#889099"></textarea></label>
<br />
<br />
<input type="submit" value="New Topic" class="btn btn-primary btn-toolbar" />
</form>
</div>
{% endblock %}

myforum/templates/myforum/signup.html
{% extends 'myforum/base.html' %}

{% block main %}
<div>
<form method="post" action="">
{% csrf_token %}
<label>Email: <br /><input type="text" name="email" /></label>
<br />
<br />
<label>Your name: <br /><input type="text" name="username" /></label>
<br />
<br />
<label>Password: <br /><input type="password" name="password" /></label>
<br />
<br />
<input type="submit" value="Sign up" class="btn btn-primary btn-toolbar" />
</form>
</div>
{% endblock %}

myforum/templates/myforum/topic.html
{% extends 'myforum/base.html' %}
{% load myforum_tags %}|

{% block main %}


<div class="topic-header">
    <h3 class="topic-title">{{ current_topic.title }}</h3>
    <p class="topic-description">{{ current_topic.description }}</p>
    <ul class="topic-meta">
        <li class="topic-meta-item"> Created by  {{ current_topic.created_by }}</li>
        <li class="topic-meta-item">on {{ current_topic.created|date:"n/j/y" }}</li>
        <li class="topic-meta-item">{{ current_topic.posts|length }} posts</li>
    </ul>
</div>

<div class="list-view" id="post-list">
    <div class="items">
    
    {% for post in current_topic.posts %}
        <div class="topic-comment clearfix" onmouseover="document.getElementById('hide_{{ post.id }}').style.display='block'" onmouseout="document.getElementById('hide_{{ post.id }}').style.display='none'">
            <div class="avatar">
                <a href="#"><img class="avatar-img" src="{{ post.avatar_url }}" style="width:31px"></a>
            </div>
            <div class="comment-data" style="padding-left: 45px;">
                <h4 class="comment-author">{{ post.created_by }}</h4>
                <p class="comment-date">{{ post.modified|date:"g:ia"|slice:":-1" }} on {{ post.modified|date:"n/j/y" }}</p>
                
                <div class="comment-content" id="comment_{{ post.id }}">
                    {{ post.content|linkbreaks|safe }}
                </div>
                
                <div style="height:16px; ">
                <p class="comment-date" style="margin-right:15px; display:none" id="hide_{{ post.id }}">
                    <!--<a href="javascript:document.getElementById('new_post').focus().scrollIntoView(true)" style="color:#889099">Reply</a> &nbsp; &nbsp;-->
                    {% if user|can_edit:post %}
                        {% url 'myforum:edit_post' post.pk as edit_url %}
                        <a href="#" onclick="edit_post_inline('{{ edit_url }}', 'comment_{{ post.id }}'); this.style.display='none'" style="color:#889099">Edit</a> &nbsp; &nbsp;
                    {% endif %}
                    {% if user|can_delete:post %}
                        <a href="{% url 'myforum:delete_post' post.pk %}" onclick="return confirm('Are you sure?')" style="color:#889099">Delete</a>
                    {% endif %}
                </p>
                </div>
            </div> <!-- .comment-data -->
        </div> <!-- .topic-comment -->
    {% endfor %}
    
    </div> <!-- .items -->
</div> <!-- #post-list -->

<div style="padding-top:20px">
<form method="post" action="">
    {% csrf_token %}
    <textarea id="new_post" name="post" style="width:500px;height:80px;color:#889099"></textarea>
    <br />
    <input type="submit" value="New Post" class="btn btn-primary btn-toolbar" />
</form>
</div>

<script type="text/javascript">
function edit_post_inline(edit_url, comment_id)
{
    document.getElementById(comment_id).innerHTML = '<iframe src="'+edit_url+'" width="620" height="200" frameborder="0" scrolling="no"></iframe>';
}

function edit_post(edit_url)
{
    var new_window = window.open(edit_url, '_blank','width=600,height=400,location=0,menubar=0,status=0,toolbar=0');
    new_window.onbeforeunload = function(){
        setTimeout('location.reload()', 600);
    }
}
</script>

{% endblock %}

myforum/templates/myforum/topics_searched.html
{% extends 'myforum/base.html' %}
{% load endless %}

{% block main %}

            <div class="topics-container">
                <div id="yw0" class="list-view">
                    <div class="items">
                        
                        {% paginate topics_searched %}
                        {% for topic in topics_searched %}
                        <div class="topic clearfix odd">
                            <h4 class="topic-title"><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></h4>
                            <p class="topic-description">{{ topic.description }}</p>
                            <ul class="topic-meta">
                                <li class="topic-meta-item"> Created by  {{ topic.created_by }}</li>
                                <li class="topic-meta-item">on {{ topic.created|date:"n/j/y" }}</li>
                                <li class="topic-meta-item">{{ topic.posts|length }} posts</li>
                            </ul>
                        </div>
                        {% empty %}
                            Nothing searched.
                        {% endfor %}
                        
                    </div> <!-- .items -->
                    
                    <br />
                    <div style="text-align: right">
                    {% show_pages %}
                    </div>
                    <br />
                    
                    <!--
                    <div class="pager">
                        <ul id="yw1" class="yiiPager">
                            <li class="first hidden"><a href="#">&lt;&lt; First</a></li>
                            <li class="previous hidden"><a href="#"><span class="pagination-left"></span></a></li>
                            <li class="page selected"><a href="#">1</a></li>
                            <li class="page"><a href="#">2</a></li>
                            <li class="next"><a href="#"><span class="pagination-right"></span></a></li>
                            <li class="last hidden"><a href="#">Last &gt;&gt;</a></li>
                        </ul>
                    </div>
                -->
                </div> <!-- .list-view -->
            </div> <!-- .topic-container -->

{% endblock %}